CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(50) NOT NULL,
  "avatar_id" int,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "region" VARCHAR(255),
  "country" VARCHAR(100) DEFAULT 'Россия',
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, region)
);

CREATE INDEX idx_cities_name ON cities(name);

INSERT INTO cities (name, region) VALUES
  ('Москва', 'Москва'),
  ('Санкт-Петербург', 'Ленинградская область');

CREATE TABLE "venues" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar(255),
  "description" text,
  "city_id" int,
  "street_address" varchar(500),
  "opening_hours" varchar(100),
  "capacity" int,
  "logo_id" int,
  "cover_photo_id" int,
  "phone" varchar(20),
  "work_email" varchar(255),
  "tg_personal_link" varchar(255),
  "tg_channel_link" varchar(255),
  "vk_link" varchar(255),
  "tiktok_link" varchar(255),
  "youtube_link" varchar(255),
  "dzen_link" varchar(255),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "creators" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar(255),
  "description" text,
  "photo_id" int,
  "phone" varchar(20),
  "work_email" varchar(255),
  "tg_personal_link" varchar(255),
  "tg_channel_link" varchar(255),
  "vk_link" varchar(255),
  "tiktok_link" varchar(255),
  "youtube_link" varchar(255),
  "dzen_link" varchar(255),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "venue_photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venue_id" int,
  "image_id" int
);

CREATE TABLE "creator_photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" int,
  "image_id" int
);

CREATE TABLE "images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "file_name" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_type" varchar(50),
  "image_type" varchar(50) NOT NULL,
  "bucket_name" varchar(100) NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" INT NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "cover_photo_id" INT,
  "status" VARCHAR(20) DEFAULT 'active',
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('active', 'booked', 'completed'))
);

CREATE INDEX idx_events_creator_id ON events(creator_id);
CREATE INDEX idx_venues_city ON venues(city_id);

CREATE TABLE "event_categories" (
  "event_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY (event_id, category_id)
);

CREATE TABLE "venue_categories" (
  "venue_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY (venue_id, category_id)
);

CREATE TABLE "applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" INT NOT NULL,
  "sender_type" VARCHAR(20) NOT NULL,
  "receiver_id" INT NOT NULL,
  "receiver_type" VARCHAR(20) NOT NULL,
  "event_id" INT NOT NULL,
  "message" TEXT,
  "status" VARCHAR(20) DEFAULT 'pending',
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('pending', 'accepted', 'rejected')),
  CHECK (sender_type IN ('creator', 'venue')),
  CHECK (receiver_type IN ('creator', 'venue'))
);

CREATE INDEX idx_applications_sender ON applications(sender_id);
CREATE INDEX idx_applications_receiver ON applications(receiver_id);
CREATE INDEX idx_applications_status ON applications(status);

ALTER TABLE "venues" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "venues" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id") ON DELETE RESTRICT;
ALTER TABLE "creators" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "venue_photos" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE;
ALTER TABLE "venue_photos" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("id");
ALTER TABLE "creator_photos" ADD FOREIGN KEY ("creator_id") REFERENCES "creators" ("id") ON DELETE CASCADE;
ALTER TABLE "creator_photos" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("id");
ALTER TABLE "users" ADD FOREIGN KEY ("avatar_id") REFERENCES "images" ("id");
ALTER TABLE "venues" ADD FOREIGN KEY ("logo_id") REFERENCES "images" ("id");
ALTER TABLE "venues" ADD FOREIGN KEY ("cover_photo_id") REFERENCES "images" ("id");
ALTER TABLE "creators" ADD FOREIGN KEY ("photo_id") REFERENCES "images" ("id");
ALTER TABLE "events" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "events" ADD FOREIGN KEY ("cover_photo_id") REFERENCES "images" ("id");
ALTER TABLE "event_categories" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;
ALTER TABLE "event_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "venue_categories" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE;
ALTER TABLE "venue_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "applications" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "applications" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "applications" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;

CREATE TABLE "collaborations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" INT NOT NULL,
  "event_id" INT NOT NULL,
  "creator_user_id" INT NOT NULL,
  "venue_user_id" INT NOT NULL,
  "status" VARCHAR(20) DEFAULT 'pending',
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('pending', 'completed', 'cancelled'))
);

CREATE INDEX idx_collaborations_creator ON collaborations(creator_user_id);
CREATE INDEX idx_collaborations_venue ON collaborations(venue_user_id);

ALTER TABLE "collaborations" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE;
ALTER TABLE "collaborations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;
ALTER TABLE "collaborations" ADD FOREIGN KEY ("creator_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "collaborations" ADD FOREIGN KEY ("venue_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;